"""create FileDB table

Revision ID: 3c81a1072801
Revises:
Create Date: 2021-05-10 23:58:50.248307

"""
from alembic import op
import sqlalchemy as sa
import local_database

# revision identifiers, used by Alembic.
revision = '3c81a1072801'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
                    sa.Column('id', local_database.models.GUID(), nullable=False),
                    sa.Column('file_name', sa.String(), nullable=False),
                    sa.Column('field_delimiter', sa.String(), server_default=',', nullable=False),
                    sa.Column('lock', sa.Boolean(), nullable=True),
                    sa.Column('last_fragment_block_size', sa.Integer(), nullable=True),
                    sa.Column('key_ranges', sa.PickleType(), nullable=True),
                    sa.Column('file_fragments', sa.PickleType(), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
                    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
