"""create Shuffle table

Revision ID: 8834b1836ea0
Revises: 3c81a1072801
Create Date: 2021-05-10 23:59:47.616455

"""
from alembic import op
import sqlalchemy as sa
import local_database


# revision identifiers, used by Alembic.
revision = '8834b1836ea0'
down_revision = '3c81a1072801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shuffle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', local_database.models.GUID(), nullable=False),
    sa.Column('list_of_min_hashes', sa.PickleType(), nullable=True),
    sa.Column('list_of_max_hashes', sa.PickleType(), nullable=True),
    sa.Column('data_nodes_processed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shuffle_id'), 'shuffle', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shuffle_id'), table_name='shuffle')
    op.drop_table('shuffle')
    # ### end Alembic commands ###
